// Lista das 30 equipas da NBA com um "OVR" (força geral) fictício para a simulação
const NBA_TEAMS = [
    { id: "bos", nome: "Boston Celtics", conf: "Leste", ovr: 93 },
    { id: "den", nome: "Denver Nuggets", conf: "Oeste", ovr: 91 },
    { id: "okc", nome: "Oklahoma City Thunder", conf: "Oeste", ovr: 92 },
    { id: "mil", nome: "Milwaukee Bucks", conf: "Leste", ovr: 87 },
    { id: "min", nome: "Minnesota Timberwolves", conf: "Oeste", ovr: 88 },
    { id: "nyk", nome: "New York Knicks", conf: "Leste", ovr: 87 },
    { id: "lac", nome: "LA Clippers", conf: "Oeste", ovr: 85 },
    { id: "dal", nome: "Dallas Mavericks", conf: "Oeste", ovr: 86 },
    { id: "phx", nome: "Phoenix Suns", conf: "Oeste", ovr: 84 },
    { id: "lal", nome: "Los Angeles Lakers", conf: "Oeste", ovr: 85 },
    { id: "cle", nome: "Cleveland Cavaliers", conf: "Leste", ovr: 88 },
    { id: "ind", nome: "Indiana Pacers", conf: "Leste", ovr: 85 },
    { id: "phi", nome: "Philadelphia 76ers", conf: "Leste", ovr: 83 },
    { id: "orl", nome: "Orlando Magic", conf: "Leste", ovr: 84 },
    { id: "mia", nome: "Miami Heat", conf: "Leste", ovr: 82 },
    { id: "nop", nome: "New Orleans Pelicans", conf: "Oeste", ovr: 81 },
    { id: "sac", nome: "Sacramento Kings", conf: "Oeste", ovr: 80 },
    { id: "gsw", nome: "Golden State Warriors", conf: "Oeste", ovr: 82 },
    { id: "hou", nome: "Houston Rockets", conf: "Oeste", ovr: 86 },
    { id: "atl", nome: "Atlanta Hawks", conf: "Leste", ovr: 79 },
    { id: "chi", nome: "Chicago Bulls", conf: "Leste", ovr: 76 },
    { id: "bkn", nome: "Brooklyn Nets", conf: "Leste", ovr: 72 },
    { id: "tor", nome: "Toronto Raptors", conf: "Leste", ovr: 77 },
    { id: "uta", nome: "Utah Jazz", conf: "Oeste", ovr: 73 },
    { id: "mem", nome: "Memphis Grizzlies", conf: "Oeste", ovr: 81 },
    { id: "sas", nome: "San Antonio Spurs", conf: "Oeste", ovr: 82 },
    { id: "por", nome: "Portland Trail Blazers", conf: "Oeste", ovr: 74 },
    { id: "cha", nome: "Charlotte Hornets", conf: "Leste", ovr: 73 },
    { id: "det", nome: "Detroit Pistons", conf: "Leste", ovr: 80 },
    { id: "was", nome: "Washington Wizards", conf: "Leste", ovr: 71 }
];
